//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Ticket = new HashSet<Ticket>();
        }

        public Client(string fullName, string passportNum)
        {
            this.Ticket = new HashSet<Ticket>();
            FullName = fullName;
            PassportNum = passportNum;
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PassportNum { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
