//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee(string password, string fullName, int adminRights)
        {
            Password = password;
            FullName = fullName;
            AdminRights = adminRights;
        }

        public int Id { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public int AdminRights { get; set; }
    }
}
