//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Interfaces.IEntity
    {
        public Employee()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<byte> UserRights { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
