//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayDataModelContainer : DbContext
    {
        public RailwayDataModelContainer()
            : base("name=RailwayDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> EmployeeSet { get; set; }
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Seat> SeatSet { get; set; }
        public virtual DbSet<Wagon> WagonSet { get; set; }
        public virtual DbSet<Train> TrainSet { get; set; }
        public virtual DbSet<Station> StationSet { get; set; }
        public virtual DbSet<WagonSeat> WagonSeatSet { get; set; }
        public virtual DbSet<TrainWagon> TrainWagonSet { get; set; }
        public virtual DbSet<Route> RouteSet { get; set; }
        public virtual DbSet<Voyage> VoyageSet { get; set; }
        public virtual DbSet<VoyageRoute> VoyageRouteSet { get; set; }
        public virtual DbSet<Ticket> TicketSet { get; set; }
    }
}
