//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayDataEntities : DbContext
    {
        public RailwayDataEntities()
            : base("name=RailwayDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Train> Train { get; set; }
        public virtual DbSet<TrainComposition> TrainComposition { get; set; }
        public virtual DbSet<TrainRoute> TrainRoute { get; set; }
        public virtual DbSet<Voyage> Voyage { get; set; }
        public virtual DbSet<Wagon> Wagon { get; set; }
        public virtual DbSet<WagonSeat> WagonSeat { get; set; }
    }
}
