//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route : Interfaces.IEntity
    {
        public Route()
        {
            this.Voyage_Route = new HashSet<VoyageRoute>();
            this.Ticket = new HashSet<Ticket>();
            this.Ticket1 = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<System.DateTime> DepartureTimeOffset { get; set; }
        public Nullable<System.DateTime> ArrivalTimeOffset { get; set; }
        public Nullable<int> StationId { get; set; }
    
        public virtual ICollection<VoyageRoute> Voyage_Route { get; set; }
        public virtual Station Station { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Ticket> Ticket1 { get; set; }
    }
}
