//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat : Interfaces.IEntity
    {
        public Seat()
        {
            this.Wagon_Seat = new HashSet<WagonSeat>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SeatNum { get; set; }
    
        public virtual ICollection<WagonSeat> Wagon_Seat { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
