//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Ticket : Interfaces.IEntity
    {
        public Ticket()
        {
            this.Voyage = new HashSet<Voyage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> TrainId { get; set; }
        public Nullable<int> WagonId { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Voyage> Voyage { get; set; }
    }
}
