//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Voyage = new HashSet<Voyage>();
        }

        public Ticket(Nullable<int> clientId
            , Nullable<int> trainId
            , Nullable<int> wagonId
            , Nullable<int> seatId
            , Nullable<double> price)
        {
            this.Voyage = new HashSet<Voyage>();

            ClientId = clientId;
            TrainId = trainId;
            WagonId = wagonId;
            SeatId = seatId;
            Price = price;
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> TrainId { get; set; }
        public Nullable<int> WagonId { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Voyage> Voyage { get; set; }
    }
}
