//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainRoute
    {
        public int Id { get; set; }
        public int TrainId { get; set; }
        public int StationId { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public double Distance { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Train Train { get; set; }
    }
}
