//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        public int Id { get; set; }
        public Nullable<int> TrainId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TicketId { get; set; }

        public Voyage(Nullable<int> trainId, Nullable<System.DateTime> _date, Nullable<int> status, Nullable<int> ticketId)
        {
            TrainId = trainId;
            Date = _date;
            Status = status;
            TicketId = ticketId;
        }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Train Train { get; set; }
    }
}
