//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage : Interfaces.IEntity
    {
        public Voyage()
        {
            this.Voyage_Route = new HashSet<VoyageRoute>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> Periodicity { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public Nullable<int> TrainId { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual ICollection<VoyageRoute> Voyage_Route { get; set; }
    }
}
