//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon : Interfaces.IEntity
    {
        public Wagon()
        {
            this.Wagon_Seat = new HashSet<WagonSeat>();
            this.Train_Wagon = new HashSet<TrainWagon>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> WagonNum { get; set; }
        public Nullable<byte> WagonType { get; set; }
    
        public virtual ICollection<WagonSeat> Wagon_Seat { get; set; }
        public virtual ICollection<TrainWagon> Train_Wagon { get; set; }
    }
}
