//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WagonSeat
    {
        public int Id { get; set; }
        public Nullable<int> WagonId { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<int> SeatNum { get; set; }

        WagonSeat(Nullable<int> wagonId, Nullable<int> seatId, Nullable<int> seatNum)
        {
            WagonId = wagonId;
            SeatId = seatId;
            SeatNum = seatNum;
        }

        public virtual Seat Seat { get; set; }
        public virtual Wagon Wagon { get; set; }
    }
}
