//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Wagon : Interfaces.IEntity
    {
        public Wagon()
        {
            this.TrainComposition = new HashSet<TrainComposition>();
            this.WagonSeat = new HashSet<WagonSeat>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WagonType { get; set; }
        public Nullable<int> SeatsAmount { get; set; }
    
        public virtual ICollection<TrainComposition> TrainComposition { get; set; }
        public virtual ICollection<WagonSeat> WagonSeat { get; set; }
    }
}
